spring:
  application:
    name: ads-loader-bot-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ads-loader-bot-bd
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          batch_size: 50
          fetch_size: 50
        c3p0:
          timeout: 10000
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  session:
    jdbc:
      initialize-schema: always

  docker:
    compose:
      file: ../ads-loader-bot-service/compose.yaml

app:
  ad-load-job:
    enabled: false


logging:
  level:
    root: INFO
    vnavesnoj.spring.database.pool: INFO
    org.springframework.jdbc.core: INFO