--liquibase formatted sql

--changeset vnavesnoj:1
INSERT INTO category(platform, name)
VALUES ('OLXUA', 'Допомога'),
       ('OLXUA', 'Дитячий світ'),
       ('OLXUA', 'Нерухомість'),
       ('OLXUA', 'Авто'),
       ('OLXUA', 'Запчастини для транспорту'),
       ('OLXUA', 'Тварини'),
       ('OLXUA', 'Дім і сад'),
       ('OLXUA', 'Електроніка'),
       ('OLXUA', 'Бізнес та послуги'),
       ('OLXUA', 'Оренда та прокат'),
       ('OLXUA', 'Мода і стиль'),
       ('OLXUA', 'Хобі, відпочинок і спорт');

--changeset vnavesnoj:2
INSERT INTO spot(platform, name, url, category_id, analyzer)
VALUES ('OLXUA', 'Допомога', 'dopomoga/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Допомога'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Потрібна допомога', 'dopomoga/potribna_dopomoha/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Допомога'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Пропоную допомогу', 'dopomoga/proponuiu_dopomohu/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Допомога'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Дитячий світ', 'detskiy-mir/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитячі коляски', 'detskiy-mir/detskie-kolyaski/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитячий одяг', 'detskiy-mir/detskaya-odezhda/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Товари для школярів', 'detskiy-mir/tovary-dlya-shkolnikov/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитячі меблі', 'detskiy-mir/detskaya-mebel/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитяче взуття', 'detskiy-mir/detskaya-obuv/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитячий транспорт', 'detskiy-mir/detskiy-transport/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інші дитячі товари', 'detskiy-mir/prochie-detskie-tovary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Іграшки', 'detskiy-mir/igrushki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Дитячі автокрісла', 'detskiy-mir/detskie-avtokresla/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Годування', 'detskiy-mir/kormlenie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дитячий світ'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Нерухомість', 'nedvizhimost/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Подобова оренда житла', 'nedvizhimost/posutochno-pochasovo/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Комерційна нерухомість', 'nedvizhimost/kommercheskaya-nedvizhimost/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Будинки', 'nedvizhimost/doma/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Гаражі, парковки', 'nedvizhimost/garazhy-parkovki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Нерухомість за кордоном', 'nedvizhimost/nedvizhimost-za-rubezhom/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Кімнати', 'nedvizhimost/komnaty/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Земля', 'nedvizhimost/zemlya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Квартири', 'nedvizhimost/kvartiry/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Нерухомість'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Авто', 'transport/', (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Легкові автомобілі', 'transport/legkovye-avtomobili/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Автобуси', 'transport/avtobusy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Сільгосптехніка', 'transport/selhoztehnika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мото', 'transport/moto/', (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Водний транспорт', 'transport/vodnyy-transport/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Автомобілі з Польщі', 'transport/avtomobili-iz-polshi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інший транспорт', 'transport/drugoy-transport/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Причепи / будинки на колесах', 'transport/pritsepy-doma-na-kolesah/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Вантажівки та спецтехніка з Польщі', 'transport/gruzoviki-i-spetstehnika-iz-polshi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Вантажні автомобілі', 'transport/gruzovye-avtomobili/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Спецтехніка', 'transport/spetstehnika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Авто'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Запчастини для транспорту', 'zapchasti-dlya-transporta/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Шини, диски і колеса', 'zapchasti-dlya-transporta/shiny-diski-i-kolesa/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мотоаксесуари', 'zapchasti-dlya-transporta/motoaksessuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Транспорт на запчастини / авторозбірки',
        'zapchasti-dlya-transporta/transport-na-zapchasti-avtorazborki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Запчастини для іншої техніки', 'zapchasti-dlya-transporta/prochie-zapchasti/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Аксесуари для авто', 'zapchasti-dlya-transporta/aksessuary-dlya-avto/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Автозапчастини', 'zapchasti-dlya-transporta/avtozapchasti/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мотозапчастини', 'zapchasti-dlya-transporta/motozapchasti/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Автозвук та мультимедіа', 'zapchasti-dlya-transporta/avtozvuk-i-multimedia/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мастила та автохімія', 'zapchasti-dlya-transporta/masla-i-avtokhimiya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мотоекіпірування', 'zapchasti-dlya-transporta/motoekipirovka/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'GPS-навігатори / відеореєстратори', 'zapchasti-dlya-transporta/gps-navigatory-videoregistratory/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Запчастини для транспорту'),
        'OLX_UA_DEFAULT'),

       ('OLXUA', 'Тварини', 'zhivotnye/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Собаки', 'zhivotnye/sobaki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Бюро знахідок', 'zhivotnye/byuro-nahodok/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Рептилії', 'zhivotnye/reptilii/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Коти', 'zhivotnye/koshki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'В''язка', 'zhivotnye/vyazka/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Акваріумістика', 'zhivotnye/akvariumnye-rybki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інші тварини', 'zhivotnye/drugie-zhivotnye/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Пташки', 'zhivotnye/ptitsy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Сільгосп тварини', 'zhivotnye/selskohozyaystvennye-zhivotnye/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Зоотовари', 'zhivotnye/tovary-dlya-zhivotnyh/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Гризуни', 'zhivotnye/gryzuny/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Безкоштовно (тварини і в''язка)', 'zhivotnye/besplatno-zhivotnye-i-vyazka/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Тварини'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Дім і сад', 'dom-i-sad/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Кімнатні рослини', 'dom-i-sad/komnatnye-rasteniya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Продукти харчування / напої', 'dom-i-sad/produkty-pitaniya-napitki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Будівництво / ремонт', 'dom-i-sad/stroitelstvo-remont/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Меблі', 'dom-i-sad/mebel/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Господарський інвентар / побутова хімія', 'dom-i-sad/hozyaystvennyy-inventar/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інструменти', 'dom-i-sad/instrumenty/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Предмети інтер''єру', 'dom-i-sad/predmety-interera/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Садовий інвентар', 'dom-i-sad/sadovyy-inventar/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Посуд / кухонне приладдя', 'dom-i-sad/posuda-kuhonnaya-utvar/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інші товари для дому', 'dom-i-sad/prochie-tovary-dlya-doma/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Канцтовари / витратні матеріали', 'dom-i-sad/kantstovary-rashodnye-materialy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Сад / город', 'dom-i-sad/sad-ogorod/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Дім і сад'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Електроніка', 'elektronika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Комп''ютери та комплектуючі', 'elektronika/kompyutery-i-komplektuyuschie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Техніка для дому', 'elektronika/tehnika-dlya-doma/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Аудіотехніка', 'elektronika/audiotehnika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Ноутбуки та аксесуари', 'elektronika/noutbuki-i-aksesuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Телефони та аксесуари', 'elektronika/telefony-i-aksesuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Індивідуальний догляд', 'elektronika/individualnyy-uhod/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Тв / відеотехніка', 'elektronika/tv-videotehnika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Планшети / ел. книги та аксесуари', 'elektronika/planshety-el-knigi-i-aksessuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Ігри та ігрові приставки', 'elektronika/igry-i-igrovye-pristavki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Кліматичне обладнання', 'elektronika/klimaticheskoe-oborudovanie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Фото / відео', 'elektronika/foto-video/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Техніка для кухні', 'elektronika/tehnika-dlya-kuhni/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Аксесуари й комплектуючі', 'elektronika/aksessuary-i-komplektuyuschie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інша електроніка', 'elektronika/prochaja-electronika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Електроніка'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Бізнес та послуги', 'uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Продаж бізнесу', 'uslugi/prodazha-biznesa/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Будівництво та ремонт', 'uslugi/stroitelstvo-otdelka-remont/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Послуги для тварин', 'uslugi/uslugi-dlya-zhivotnyh/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Сировина / матеріали', 'uslugi/syre-materialy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Організація свят', 'uslugi/organizatsiya-prazdnikov/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Продаж обладнання для бізнесу', 'uslugi/oborudovanie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Туризм / іміграція', 'uslugi/turizm-immigratsiya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Фото та відеозйомка', 'uslugi/razvlechenie-foto-video/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Ремонт та обслуговування техніки', 'uslugi/remont-i-obsluzhivanie-tehniki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Ритуальні послуги', 'uslugi/ritualnye-uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Авто / мото послуги', 'uslugi/avto-moto-uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Перевезення та послуги спецтехніки', 'uslugi/perevozki-arenda-transporta/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Послуги освіти та спорту', 'uslugi/obrazovanie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Побутові послуги', 'uslugi/bytovye-uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прийом вторсировини', 'uslugi/priem-vtorsyrya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інші послуги', 'uslugi/prochie-uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Краса / здоров''я', 'uslugi/krasota-zdorove/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Догляд за дітьми та літніми людьми', 'uslugi/nyani-sidelki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Клінінг', 'uslugi/klining/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Ділові послуги', 'uslugi/delovye-uslugi/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Бізнес та послуги'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Оренда та прокат', 'arenda-prokat/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Оренда транспорту та спецтехніки', 'arenda-prokat/transport-spetstehnika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат товарів мед призначення', 'arenda-prokat/tovary-med-naznacheniya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат одягу та аксесуарів', 'arenda-prokat/odezhda-aksessuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат велосипедів і мото', 'arenda-prokat/velosipedy-moto/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат техніки та електроніки', 'arenda-prokat/tehnika-elektronika/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат дитячого одягу та товарів', 'arenda-prokat/detskaya-odezhda-tovary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Оренда обладнання', 'arenda-prokat/oborudovanie/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат товарів для заходів', 'arenda-prokat/tovary-dlya-meropriyatiy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інші товари на прокат', 'arenda-prokat/drugoe/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат інструментів', 'arenda-prokat/instrumenty/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Прокат спорт і туристичних товарів', 'arenda-prokat/sport-turisticheskie-tovary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Оренда та прокат'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Мода і стиль', 'moda-i-stil/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Краса / здоров''я', 'moda-i-stil/krasota-zdorove/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Подарунки', 'moda-i-stil/podarki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Одяг для вагітних', 'moda-i-stil/odezhda-dlya-beremennyh/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Жіночий одяг', 'moda-i-stil/zhenskaya-odezhda/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Для весілля', 'moda-i-stil/dlya-svadby/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мода різне', 'moda-i-stil/moda-raznoe/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Головні убори', 'moda-i-stil/golovnye-ubory/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Чоловічий одяг', 'moda-i-stil/muzhskaya-odezhda/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Аксесуари', 'moda-i-stil/aksessuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Чоловіча білизна та плавки', 'moda-i-stil/muzhskoe-bele-plavki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Чоловіче взуття', 'moda-i-stil/muzhskaya-obuv/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Спецодяг, спецвзуття та аксесуари', 'moda-i-stil/spetsodezhda-i-spetsobuv/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Наручні годинники', 'moda-i-stil/naruchnye-chasy/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Жіноча білизна та купальники', 'moda-i-stil/zhenskoe-bele-kupalniki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),
       ('OLXUA', 'Жіноче взуття', 'moda-i-stil/zhenskaya-obuv/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Мода і стиль'), 'OLX_UA_DEFAULT'),

       ('OLXUA', 'Хобі, відпочинок і спорт', 'hobbi-otdyh-i-sport/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Музичні інструменти', 'hobbi-otdyh-i-sport/muzykalnye-instrumenty/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Пошук попутників', 'hobbi-otdyh-i-sport/poisk-poputchikov/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Інше', 'hobbi-otdyh-i-sport/drugoe/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Книги / журнали', 'hobbi-otdyh-i-sport/knigi-zhurnaly/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Пошук гуртів / музикантів', 'hobbi-otdyh-i-sport/poisk-grupp-muzykantov/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Мілітарія', 'hobbi-otdyh-i-sport/militariya/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Антикваріат / колекції', 'hobbi-otdyh-i-sport/antikvariat-kollektsii/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'CD / DVD / Платівки', 'hobbi-otdyh-i-sport/cd-dvd-plastinki/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Вело', 'hobbi-otdyh-i-sport/velo/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Квитки', 'hobbi-otdyh-i-sport/bilety/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Спорт / відпочинок', 'hobbi-otdyh-i-sport/sport-otdyh/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT'),
       ('OLXUA', 'Квадрокоптери та аксесуари', 'hobbi-otdyh-i-sport/kvadrokoptery-i-aksessuary/',
        (SELECT id FROM category c WHERE c.platform = 'OLXUA' AND c.name = 'Хобі, відпочинок і спорт'),
        'OLX_UA_DEFAULT');